name: core
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  #The following adds flutter_bloc as state management solution
  #package url:- https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^8.0.1

  #The following helps to implement value based equality without needing to explicitly override == and hashCode.
  #package url:- https://pub.dev/packages/equatable
  equatable: ^2.0.3

  #Simple direct Service Locator that allows to decouple the interface
  #from a concrete implementation and to access the concrete implementation from everywhere in your App"
  #package url:- https://pub.dev/packages/get_it
  get_it: ^7.2.0

  #A powerful Http client for Dart, which supports Interceptors,
  #FormData, Request Cancellation, File Downloading, Timeout etc
  #package url:- https://pub.dev/packages/dio
  dio: ^4.0.6

  #A simple package to check when the device is connected (connectivity) to internet.
  #Also provide a method to listen for connection status changes.
  #package url:- https://pub.dev/packages/simple_connection_checker
  simple_connection_checker: ^0.2.1

  #Flutter plugin for reading and writing simple key-value pairs.
  #Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  #package url:- https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.0.15

  #A package which simplifies the task of updating your Flutter app's launcher icon.
  #Run the command to generate
  #flutter pub get
  #flutter pub run flutter_launcher_icons:main
  #package url:- https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: "^0.9.2"

  #A mock framework inspired by Mockito with APIs for Fakes, Mocks, behavior verification, and stubbing.
  #package url:- https://pub.dev/packages/mockito
  mockito: ^5.2.0

  #Following converts enums to String
  #package url:- https://pub.dev/packages/enum_to_string
  enum_to_string: ^2.0.1

  #Collections and utilities functions and classes related to collections.
  #package url:- https://pub.dev/packages/collection
  collection: ^1.15.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  #A build system for Dart code generation and modular compilation.
  #package url:- https://pub.dev/packages/build_runner
  build_runner: ^2.1.11

  #A simple to use mocking package for Dio intended to be used in tests.
  #It provides various types and methods to declaratively mock request-response communication.
  #package url:- https://pub.dev/packages/http_mock_adapter
  http_mock_adapter: ^0.3.2

  #A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
  #package url:- https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.5.3+2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

